### ISSUE TITLE
Images Not Displaying

### ISSUE THREAD

**Issue by ghost** [BugHunter2k/grav-plugin-cclinker#1]
Not sure if this is related to the issue. In your instructions the very first example ... 

"Simple plugin to create links to creative-common licences. All you need to do is adding e.g. [CC-BY-SA] to your content and the plugin creates an Link (text, images, buttons) with title and link to the corresponding deed."

... has a dash between the "CC" and "BY-SA", but in the rest of the instructions, there is no dash.

I've tried both ways, yet the images do not show (see attachment)

Did I miss something obvious, suggestions?

![capture](https://cloud.githubusercontent.com/assets/5008228/14862170/de222bec-0c75-11e6-82c9-5a0d5e5bc6a0.PNG)

**Comment by BugHunter2k** [comment]
The dash between cc and by-by-sa is optional. 
Can you provide a link to your page?  May be the image urls are not correct.
I'll take a deeper look at your issue tomorrow.

Ive just seen that I  have got the same problem now on my club page. Do you have Multilanguage enabled?

**Comment by ghost** [comment]
Yes, I'm using a theme that has it enabled by default.

**Comment by ghost** [comment]
Sorry, that would be incorrect, no Multilanguage installed.

**Comment by ghost** [comment]
The website page is ... http://www.mettle-endeavors.com/blog/project-clockworlds-world-map-beta-1 ... bottom blog post.

**Comment by BugHunter2k** [comment]
Added a fix to master-branch, can you check if it fixes your problem?

**Comment by ghost** [comment]
Yes, all Output Formats are now working fine. THX!

**Comment by BugHunter2k** [comment]
Fixed in v0.5.1
