### ISSUE TITLE
Images not working again?

### ISSUE THREAD

**Issue by paulhibbitts** [BugHunter2k/grav-plugin-cclinker#3]
Thanks so much for this plugin. I am working on a skeleton for using Grav to host open educational resources and this is a great little plugin to find!

I can't seem to get any images to work though for showing the licenses. A text-only license works fine, but all other options seem to produce empty rectangles. I am using Grav 1.1.12 and also am trying it out with the Gantry 5 plugin.

Thanks very much,
Paul

**Comment by BugHunter2k** [comment]
Hey Paul, 
sorry for the late reply, I've been on vacation the last days.

There has been a problem with multi-language setup in the past, do you have multilanguage enabled?
Are the image-paths on the frontend correct?

I'll have a look at this when I get home from work.

**Comment by paulhibbitts** [comment]
Thanks very much for taking a look. No, I am not working with a multi-language setup.

Please let me know if you find anything, and I'd be happy to test any possible fixes.

ps - I am also working on a CC License Particle for Gantry that you might be interested in: https://github.com/hibbitts-design/grav-gantry5-particle-cc-license

**Comment by BugHunter2k** [comment]
Hi Paul, 

I've just fiddled around a little bit on a fresh install but can't reproduce the missing images. 
May be there is a conflicting plugin or a configuration I didn't have. 
Could you provide some more information or a copy of your user folder?

**Comment by paulhibbitts** [comment]
Sure thing, here is my user folder.
[user.zip](https://github.com/BugHunter2k/grav-plugin-cclinker/files/699829/user.zip)

Thanks again,
Paul

**Comment by BugHunter2k** [comment]
There has to be something broken somewere else. 
The images are working on my test-install: https://ccbuttons.bughunter2k.de/blog/open-blogging-1-2-3

But I've no idea where to look.

**Comment by paulhibbitts** [comment]
Thanks so much for taking the time to look into it, I will continue to try things on my end and see. I assume you are running latest version of Grav etc.?

Here is my test install: http://test.hibbittsdesign.org/grav-skeleton-open-blog-site/

**Comment by BugHunter2k** [comment]
It seems the installation in a subdirectory causes the bug. 
I'm using the grav-locator to determine the path of the images
```
$locator = GravTrait::getGrav()['locator'];
$path = "/".$locator->findResource('plugin://cclinker/images/', false)."/";
```
Actually I'm not sure what has to be changed. I'm still trying to figure out.

**Comment by BugHunter2k** [comment]
Hi Paul, 
found the bug and made a patch, Could you test the patch-branch on your site, please?
https://github.com/BugHunter2k/grav-plugin-cclinker/tree/BugHunter2k-patch-1

**Comment by paulhibbitts** [comment]
Excellent! The patch appears to fix things 🙂
http://test.hibbittsdesign.org/grav-skeleton-open-blog-site/

Thanks very much for addressing this issue!
Paul
